import { Express, Request, Response } from "express";
import { storage } from "../storage";
import { randomBytes } from "crypto";
import { requirePatientAuth, validateShareToken } from "../utils/security";

/**
 * Patient Routes for QR Access Management
 */
export async function registerPatientRoutes(app: Express) {
  
  /**
   * GET /api/patient/qr
   * Retrieves the current permanent QR code data for the logged-in patient.
   */
  app.get("/api/patient/qr", requirePatientAuth, async (req: Request, res: Response) => {
    const patient = (req as any).patient;

    // Generate the URL that the QR code will link to
    const protocol = req.protocol;
    const host = req.get('host');
    const qrUrl = `${protocol}://${host}/my-records?token=${patient.permanentToken}`;

    res.json({
      qrUrl,
      permanentToken: patient.permanentToken
    });
  });

  /**
   * POST /api/patient/qr/regenerate
   * Regenerates the unique permanent token and updates the patient record.
   */
  app.post("/api/patient/qr/regenerate", requirePatientAuth, async (req: Request, res: Response) => {
    const patient = (req as any).patient;

    const newToken = randomBytes(16).toString('hex');
    await storage.updatePatientToken(patient.id, newToken);

    const protocol = req.protocol;
    const host = req.get('host');
    const qrUrl = `${protocol}://${host}/my-records?token=${newToken}`;

    res.json({
      message: "QR code regenerated successfully.",
      qrUrl,
      permanentToken: newToken
    });
  });

  /**
   * GET /api/patient/access
   * Endpoint meant to be called when scanning the QR code.
   * Requirement: Always requires authentication.
   */
  app.get("/api/patient/access", async (req: Request, res: Response) => {
    const { token } = req.query;
    
    if (!token) {
      return res.status(400).json({ message: "Missing access token." });
    }

    const patient = await storage.getPatientByToken(token as string);
    if (!patient) {
      return res.status(401).json({ message: "Invalid or expired QR code." });
    }

    // STRICT: Always redirect to login if no session, or dashboard if session exists
    const currentUserId = req.headers['x-user-id'] as string;

    if (currentUserId === patient.userId) {
      return res.json({ 
        authenticated: true, 
        redirect: "/user/records",
        patientName: patient.name 
      });
    } else {
      // Direct access not allowed without session
      return res.json({ 
        authenticated: false, 
        redirect: "/user/login",
        message: "Authentication required to view these private records."
      });
    }
  });

  /**
   * GET /api/patient/documents
   * List all documents belonging to a patient.
   */
  app.get("/api/patient/documents", requirePatientAuth, async (req: Request, res: Response) => {
    const patient = (req as any).patient;
    const docs = await storage.getDocumentsByPatient(patient.id);
    res.json(docs);
  });

  /**
   * GET /api/patient/share/history
   * List all sharing links generated by the patient.
   */
  app.get("/api/patient/share/history", requirePatientAuth, async (req: Request, res: Response) => {
    const patient = (req as any).patient;
    const history = await storage.getShareHistoryByPatient(patient.id);
    res.json(history);
  });

  /**
   * POST /api/patient/share
   * Generate a temporary sharing token with selected documents and expiry.
   */
  app.post("/api/patient/share", requirePatientAuth, async (req: Request, res: Response) => {
    const patient = (req as any).patient;
    const { documentIds, expiryHours } = req.body;

    if (!documentIds || !Array.isArray(documentIds)) {
      return res.status(400).json({ message: "No documents selected for sharing." });
    }

    const token = randomBytes(12).toString('hex');
    const expiryTime = new Date();
    expiryTime.setHours(expiryTime.getHours() + (expiryHours || 1));

    const shareToken = await storage.createShareToken({
      patientId: patient.id,
      token,
      documentIds,
      expiryTime,
      isUsed: false,
      permissions: 'READ'
    });

    const protocol = req.protocol;
    const host = req.get('host');
    const shareUrl = `${protocol}://${host}/share/${token}`;

    res.json({
      shareUrl,
      token,
      expiryTime: shareToken.expiryTime
    });
  });

  /**
   * POST /api/patient/share/revoke
   * Delete a specific share link.
   */
  app.post("/api/patient/share/revoke", requirePatientAuth, async (req: Request, res: Response) => {
    const patient = (req as any).patient;
    const { tokenId } = req.body;

    if (!tokenId) {
      return res.status(400).json({ message: "Missing token ID." });
    }

    // Security check: ensure the token belongs to this patient
    const allTokens = await storage.getShareHistoryByPatient(patient.id);
    const exists = allTokens.find(t => t.id === tokenId);

    if (!exists) {
      return res.status(403).json({ message: "Unauthorized. You cannot revoke this token." });
    }

    await storage.revokeShareToken(tokenId);
    res.json({ message: "Sharing link revoked successfully." });
  });

  /**
   * GET /api/share/:token
   * Validates a sharing token and returns the linked documents.
   * Updates access tracking.
   */
  app.get("/api/share/:token", async (req: Request, res: Response) => {
    const { token } = req.params as { token: string };
    
    const validation = await validateShareToken(token);
    if (!validation.valid) {
      return res.status(validation.status || 401).json({ message: validation.message });
    }

    const shareToken = validation.shareToken!;
    
    // Tracking: Update accessedAt
    await storage.updateShareTokenAccess(shareToken.id);

    const documents = await storage.getDocumentsByIds(shareToken.documentIds as string[]);

    res.json({
      documents,
      sharedAt: shareToken.createdAt,
      expiresAt: shareToken.expiryTime
    });
  });
}
